# 텐서(Tensor)
##### 텐서는 배열이나 행렬과 매우 유사한 특수한 자료구조다. PyTorch에서는 텐서를 사용하여 모델의 입력, 출력, 그리고 모델의 매개변수들을 부호화(Encode)한다.

##### 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 Numpy의 ndarry와 매우 유사하다. 그리고 자동 미분(Autograd)에 최적화되어 있다.

In [2]:
import torch
import numpy as np

## 텐서(Tensor) 초기화
##### 텐서는 여러가지 방법으로 초기화할 수 있다.
**1) 데이터로부터 직접(directly) 생성하기**
##### 데이터로부터 직접 텐서를 생성할 수 있다. 데이터의 자료형은 자동으로 유추한다.

In [3]:
data = [[1,2,],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**2) Numpy 배열로부터 생성하기**
##### 텐서는 NumPy 배열로 생성할 수 있다.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**3) 다른 텐서로부터 생성하기**
##### 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양, 자료형)을 유지한다.

In [10]:
# x_data 속성 유지
x_ones = torch.ones_like(x_data)
print(x_ones)

# x_data 속성을 덮음.
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9147, 0.2973],
        [0.0554, 0.3662]])


**4) 무작위 또는 상수 값을 사용하기**
##### shape은 텐서의 차원을 나타내는 튜플로, 출력 텐서의 차원을 결정한다.

In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0525, 0.9145, 0.4872],
        [0.2095, 0.4504, 0.0277]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성(Attribute)
##### 텐서의 속성은 텐서의 모양, 자료형 및 어느 장치에 저장되는지 나타낸다.

In [12]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


## 텐서 연산(Operation)
##### 전치, 인덱스, 슬라이싱, 수학 계산, 선형 대수, 임의 샘플링 등 많은 연산들이 가능하다.
##### 기본적으로 텐서는 CPU에서 생성되지만 .to 메소드를 사용하여 명시적으로 GPU로 이동 가능하다.

In [13]:
# GPU가 존재하면 텐서를 이동한다.
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

**1) NumPy식의 표준 인덱싱과 슬라이싱**

In [14]:
tensor = torch.ones(4,4)
print(tensor)
print(tensor[0])
print(tensor[:, 0])
print(tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기**
##### torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있다. (≒torch.stack)

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산(Arithmetic operations)**

In [16]:
# 두 텐서간의 행렬 곱 계산, y1 = y2 = y3
# tensor.T는 텐서의 전치를 반환
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱을 계산, z1 = z2 = z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일-요소 텐서**
##### 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 Python 숫자 값으로 변환 가능하다.

In [18]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기 연산**
##### 연산 결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라 하고, _ 접미사를 갖는다.
##### 주의사항 : 기록이 즉시 삭제되어 도함수 계산에 문제가 생길수도 있다.

In [19]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환(Bridge)
##### CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.
### 텐서를 NumPy 배열로 변환하기

In [20]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [22]:
# 텐서의 변경사항이 NumPy 배열에 반영된다.
t.add_(1)
print(t)
print(n)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


### NumPy 배열을 텐서로 변환하기

In [24]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [26]:
# NumPy 배열의 변경 사항이 텐서에 반영된다.
np.add(n, 1, out=n)
print(t)
print(n)

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
