# Introduction to PyTorch Tensors

In [1]:
import torch
import math

## Creating Tensors

In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


## Random Tensors and Seeding

In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## Tensor Shapes

In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [7]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


## Tensor Data Types

In [9]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


## Math & Logic with PyTorch Tensors

In [10]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [11]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


## In Brief: Tensor Broadcasting

In [12]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


In [14]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.3788, 0.4567],
         [0.0649, 0.6677],
         [0.7826, 0.1332]],

        [[0.3788, 0.4567],
         [0.0649, 0.6677],
         [0.7826, 0.1332]],

        [[0.3788, 0.4567],
         [0.0649, 0.6677],
         [0.7826, 0.1332]],

        [[0.3788, 0.4567],
         [0.0649, 0.6677],
         [0.7826, 0.1332]]])
tensor([[[0.0023, 0.0023],
         [0.4945, 0.4945],
         [0.3857, 0.3857]],

        [[0.0023, 0.0023],
         [0.4945, 0.4945],
         [0.3857, 0.3857]],

        [[0.0023, 0.0023],
         [0.4945, 0.4945],
         [0.3857, 0.3857]],

        [[0.0023, 0.0023],
         [0.4945, 0.4945],
         [0.3857, 0.3857]]])
tensor([[[0.9883, 0.4762],
         [0.9883, 0.4762],
         [0.9883, 0.4762]],

        [[0.9883, 0.4762],
         [0.9883, 0.4762],
         [0.9883, 0.4762]],

        [[0.9883, 0.4762],
         [0.9883, 0.4762],
         [0.9883, 0.4762]],

        [[0.9883, 0.4762],
         [0.9883, 0.4762],
         [0.9883, 0.4762]]])


In [17]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 3) # dimensions must match last-to-first

c = a * torch.rand(2, 3) # both 3rd & 2nd dims different

d = a * torch.rand((0, )) # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

## More Math with Tensors

In [16]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions :')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine :')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR :')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison :')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2) # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops :')
print(torch.max(d)) # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d)) # average
print(torch.std(d)) # standard deviation
print(torch.prod(d)) # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.]) # x unit vector
v2 = torch.tensor([0., 1., 0.]) # y unit vector
m1 = torch.rand(2, 2) # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices :')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3) # 3 times m1
print(torch.svd(m3))  # singular value decomposition

Common functions :
tensor([[0.5340, 0.6881, 0.8008, 0.2010],
        [0.2648, 0.8928, 0.9773, 0.0365]])
tensor([[-0., 1., 1., -0.],
        [1., 1., -0., 1.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0.,  0., -1.,  0.]])
tensor([[-0.5000,  0.5000,  0.5000, -0.2010],
        [ 0.2648,  0.5000, -0.5000,  0.0365]])

Sine and arcsine :
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR :
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison :
tensor([[ True, False],
        [False, False]])

Reduction ops :
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices :
tensor([ 0.,  0., -1.])
tensor([[0.9807, 0.6545],
        [0.4144, 0.0696]])
tensor([[2.9421, 1.9635],
        [1.2431, 0.2089]])
torch.return_types.svd(
U=tensor([[-0.9492, -0.3146],
        [-0.3146,  0.9492]]),
S=tensor([3.7228, 0.4906]),
V=tensor([[-0.8552,  0.5183],
        [-0.5183, -0.8552]]))

## Altering Tensors in Place

In [18]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a :')
print(a)
print(torch.sin(a)) # this operation creates a new tensor in memory
print(a) # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb :')
print(b)
print(torch.sin_(b)) # note the underscore
print(b) # b has changed

a :
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b :
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [19]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before :')
print(a)
print(b)
print('\nAfter adding :')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before :
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7765, 0.3534],
        [0.7016, 0.6826]])

After adding :
tensor([[1.7765, 1.3534],
        [1.7016, 1.6826]])
tensor([[1.7765, 1.3534],
        [1.7016, 1.6826]])
tensor([[0.7765, 0.3534],
        [0.7016, 0.6826]])

After multiplying
tensor([[0.6030, 0.1249],
        [0.4923, 0.4660]])
tensor([[0.6030, 0.1249],
        [0.4923, 0.4660]])


In [20]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out = c)
print(c) # contents of c have changed

assert c is d # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c) # c has changed again
assert id(c) == old_id # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.8606, 0.6549],
        [0.9642, 0.7363]])
tensor([[0.5874, 0.4363],
        [0.6339, 0.3208]])


## Copying Tensors

In [21]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561 # we change a...
print(b) # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [22]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory...
print(torch.eq(a, b)) # ...but still with the same contents!

a[0][1] = 561 # a changes...
print(b) # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [23]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.4323, 0.1811],
        [0.6962, 0.8073]], requires_grad=True)
tensor([[0.4323, 0.1811],
        [0.6962, 0.8073]], grad_fn=<CloneBackward0>)
tensor([[0.4323, 0.1811],
        [0.6962, 0.8073]])
tensor([[0.4323, 0.1811],
        [0.6962, 0.8073]], requires_grad=True)


## Moving to GPU

In [25]:
if torch.cuda.is_available():
    print('We have a GPU ! ')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [26]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device = 'cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [27]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device : {}'.format(my_device))

x = torch.rand(2, 2, device = my_device)
print(x)

Device : cpu
tensor([[0.2125, 0.3977],
        [0.3132, 0.6331]])


In [28]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [29]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device = 'gpu')
z = x + y  # exception will be thrown

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu

## Changing the Number of Dimensions

In [30]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [31]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.6503]]]]])


In [32]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.4621, 0.6882, 0.7282, 0.9156, 0.4836, 0.1451, 0.7946, 0.4126, 0.1625,
         0.9214, 0.2327, 0.5813, 0.7089, 0.3735, 0.9389, 0.3442, 0.9211, 0.6042,
         0.7966, 0.6166]])
torch.Size([20])
tensor([0.4621, 0.6882, 0.7282, 0.9156, 0.4836, 0.1451, 0.7946, 0.4126, 0.1625,
        0.9214, 0.2327, 0.5813, 0.7089, 0.3735, 0.9389, 0.3442, 0.9211, 0.6042,
        0.7966, 0.6166])
torch.Size([2, 2])
torch.Size([2, 2])


In [33]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.7051, 0.7051],
         [0.5522, 0.5522],
         [0.2367, 0.2367]],

        [[0.7051, 0.7051],
         [0.5522, 0.5522],
         [0.2367, 0.2367]],

        [[0.7051, 0.7051],
         [0.5522, 0.5522],
         [0.2367, 0.2367]],

        [[0.7051, 0.7051],
         [0.5522, 0.5522],
         [0.2367, 0.2367]]])


In [34]:
a = torch.ones(4, 3, 2)
b = torch.rand(3) # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1) # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c) # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.5497, 0.5497],
         [0.1662, 0.1662],
         [0.2961, 0.2961]],

        [[0.5497, 0.5497],
         [0.1662, 0.1662],
         [0.2961, 0.2961]],

        [[0.5497, 0.5497],
         [0.1662, 0.1662],
         [0.2961, 0.2961]],

        [[0.5497, 0.5497],
         [0.1662, 0.1662],
         [0.2961, 0.2961]]])


In [35]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [36]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


## NumPy Bridge

In [37]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [38]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5058, 0.0309, 0.8954],
        [0.6322, 0.8446, 0.6683]])
[[0.50579756 0.03087026 0.8954111 ]
 [0.63219327 0.84463984 0.6683168 ]]


In [39]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.50579756  0.03087026  0.8954111 ]
 [ 0.63219327 17.          0.6683168 ]]
